### PR TITLE
Delete the guest queue when deleting an instance.

### PR DESCRIPTION
**Pull request by TimSimpsonR**
- Added a "delete_queue" method to the guestagent.api.
- Added a "delete_queue" method to reddwarf.rpc, which is currently only implemented in kombu.

### CODE REVIEW

**Comment by TimSimpsonR** [comment]
Hold off on merging, the tests are coming in a bit...

**Comment by rnirmal** [comment]
+1

**Comment by hub-cap** [comment]
nice dude +1

**Comment by TimSimpsonR** [comment]
Pull request for RDLI tests: https://github.com/hub-cap/reddwarf_lite-integration/pull/102

**Comment by cp16net** [comment]
+1

**Comment by ed-** [comment]
+1

**Pull request merged**
