### PR TITLE
Changing the max_instances_per_user to 55 in the test config file.

### PR DESCRIPTION
**Pull request by TimSimpsonR**

### CODE REVIEW

**Comment by ed-** [comment]
+5

**Comment by imsplitbit** [comment]
+1

**Comment by imsplitbit** [comment]
+1

**Comment by cp16net** [comment]
55? thats like \* 11!

**Comment by cp16net** [comment]
+1

**Comment by hub-cap** [comment]
Cue the bad music. Fiffffffty fiiiiiiive.

**Pull request merged**
