### PR TITLE
regexing xml data to remove extra space & newlines

### PR DESCRIPTION
**Pull request by hub-cap**

### CODE REVIEW

**Comment by hub-cap** [comment]
Yes this is nasty. The alternative is to fix openstack-common wsgi, which we will need to eventually do. It feels dirty to fix it this way. Ive created a issue regarding it to make a better fix and push it upstream in the future.

**Comment by hub-cap** [comment]
Just for the record this is the first bit of code that diverges between XML and JSON. This is the first bit o code that is specific to XML, which is the problem child here :D

**Comment by cp16net** [comment]
thats not as dirty as i expected but i know what you mean.

**Comment by cp16net** [comment]
+1

**Comment by hub-cap** [comment]
@cp16net youre right its worse :P

**Comment by imsplitbit** [comment]
+1

**Comment by ed-** [comment]
ugly but +1 anyway so long as this remains a stopgap

**Comment by hub-cap** [comment]
Changing this since its on old code and in the wrong place

**Pull request closed without merging**
