### PR TITLE
Give the nova instance the real hostname if we've got it.

### PR DESCRIPTION
**Pull request by ed-**
Turns out it's that easy.

### CODE REVIEW

**Comment by rnirmal** [comment]
+1

**Comment by hub-cap** [comment]
It's not that easy. When u do a get now on the instance u won't get the name that was set by them. Like I told u already, this will require a new field in the db that we use to return the "name" they gave us.

**Comment by hub-cap** [comment]
But as for the setting it, it is that easy. :)

**Comment by TimSimpsonR** [comment]
+1

**Comment by cp16net** [comment]
+1

**Comment by imsplitbit** [comment]
+1

**Comment by ed-** [comment]
We already have and use a name field. The only change here is if our hostname isn't null, we give it to nova. If our hostname is null, we just give them our name. Our own records don't change, we already report at least the name, and the hostname if we have it.

**Pull request merged**
