### PR TITLE
Some more PEP8 fixes to make tox happy.

### PR DESCRIPTION
**Pull request by ed-**
As requested.

### CODE REVIEW

**Comment by cp16net** [comment]
This is good but i am not sure that it fixes the issue we saw in CI.

**Comment by jcru** [comment]
+1

**Comment by ed-** [comment]
This will fix _some_ of the issues seen in CI last week.

**Comment by cp16net** [comment]
+1

**Comment by imsplitbit** [comment]
+1

**Comment by TimSimpsonR** [comment]
@ed- I was about to merge this!

**Comment by cp16net** [comment]
lolz i +1 it...

**Pull request closed without merging**
