### PR TITLE
Removing hostname from list instances

### PR DESCRIPTION
**Pull request by rnirmal**

### CODE REVIEW

**Comment by ed-** [comment]
+1

**Comment by hub-cap** [comment]
+1

**Comment by TimSimpsonR** [comment]
It seems like the model should handle something such as whether to attach a hostname, and the views should just display it if the attribute is there. This way its easier to see the bug if, for example, the option is disabled and hostnames are getting attached to the model regardless.

**Comment by cp16net** [comment]
+1

**Comment by imsplitbit** [comment]
+1

**Comment by TimSimpsonR** [comment]
+1

**Pull request merged**
