### PR TITLE
Reversing the order of the dns save

### PR DESCRIPTION
**Pull request by hub-cap**

### CODE REVIEW

**Comment by hub-cap** [comment]
This does _not_ permanently fix the issue w/ the hostname. Its a stopgap to make sure null doesnt come back

**Comment by cp16net** [comment]
rebase! +1

edit: or maybe not...

**Comment by ed-** [comment]
+1

**Comment by rnirmal** [comment]
+1

**Comment by hub-cap** [comment]
extreme wickedness

**Comment by TimSimpsonR** [comment]
+1

**Pull request merged**
