### PR TITLE
Added another flavor to what gets returned in fake mode.

### PR DESCRIPTION
**Pull request by TimSimpsonR**
This is a sibling to https://github.com/hub-cap/reddwarf_lite-integration/pull/63 and makes fake mode compatible with the test data.

### CODE REVIEW

**Comment by TimSimpsonR** [comment]
This kind of makes it clear fake mode should be data driven... will do eventually I guess.

**Comment by hub-cap** [comment]
+1

**Comment by ed-** [comment]
+1

**Comment by cp16net** [comment]
+1

**Comment by rnirmal** [comment]
+1

**Pull request merged**
