### PR TITLE
Add reset-password action and return Not Implemented

### PR DESCRIPTION
**Pull request by vipulsabhaya**
Aligns with the changes to reddwarfclient to add a reset-password action

### CODE REVIEW

**Comment by ed-** [comment]
There we go

+1

**Comment by rnirmal** [comment]
+1

**Comment by imsplitbit** [comment]
forgive my ignorance but why do we need to add this if it's just raising not implemented?

**Comment by vipulsabhaya** [comment]
This is one of the APIs that's available in our (HP) implementation, which is not in the base RedDwarf API.  We also have another set of APIs related to Snapshots that we'll be submitting as well.

**Comment by cp16net** [comment]
It would be really nice if we could get to a point where we can make extensions similar to nova style (or better) for api calls.

+1

**Comment by jcru** [comment]
+1

**Comment by pdmars** [comment]
+1

**Comment by hub-cap** [comment]
@vipulsabhaya we will merge this. Give me a bit of time to explain to the team about the NotImplemented strategy :D

**Comment by vipulsabhaya** [comment]
@hub-cap awesome, good to hear!

**Pull request merged**
