### PR TITLE
Fixing the extensions to behave like existing reddwarf.

### PR DESCRIPTION
**Pull request by hub-cap**
- Fixed the mappers in the extensions
- Added unprocessable entity raise to the extensions
- Fixed small bug is is_sql_enabled

### CODE REVIEW

**Comment by TimSimpsonR** [comment]
+1

**Comment by cp16net** [comment]
schema instead of databases?

**Comment by hub-cap** [comment]
ya its called a schema in actual mysql lingo, but ill leave it databases in the url

**Comment by ed-** [comment]
+1

**Pull request merged**
