### PR TITLE
Changed link generation code.

### PR DESCRIPTION
**Pull request by TimSimpsonR**
- Flavors no longer relies on the Nova flavors api to generate links.

### CODE REVIEW

**Comment by imsplitbit** [comment]
If you do the pep8 fixes I'll plus one it.  Looks good otherwise.

**Comment by TimSimpsonR** [comment]
Thanks for pointing that out. Fixed pep8 issues.

**Comment by imsplitbit** [comment]
+1

**Comment by imsplitbit** [comment]
+1

**Comment by cp16net** [comment]
+1

**Comment by rnirmal** [comment]
+1 yay less duplication :)

**Comment by ed-** [comment]
+1 Glad to see this refactored.

**Comment by hub-cap** [comment]
+1

**Comment by sacharya** [comment]
+1

**Pull request merged**
