### PR TITLE
Moved functionality into wsgi.Controller.

### PR DESCRIPTION
**Pull request by TimSimpsonR**
- Found that classes from multiple modules were inheriting from reddwarf.instances.service.BaseController or InstanceController directly (the later of which wass probably adding bugs) and so moved all the common functionality into wsgi controller.
- Moved exceptions from other exception maps into wsgi.Controller's exception_map.

### CODE REVIEW

**Comment by hub-cap** [comment]
Nice dude! Assuming our exceptions always map out the same , which they should. +1

**Comment by hub-cap** [comment]
Nice dude! Assuming our exceptions always map out the same , which they should. +1

**Comment by ed-** [comment]
Much less confusing.

+1

**Comment by cp16net** [comment]
nice +1

**Comment by imsplitbit** [comment]
+1

**Comment by rnirmal** [comment]
+1

**Pull request merged**
