### PR TITLE
Fixing the version

### PR DESCRIPTION
**Pull request by hub-cap**
Do not merge yet, awaiting testing

### CODE REVIEW

**Comment by cp16net** [comment]
+1

**Comment by rnirmal** [comment]
+1

**Comment by sacharya** [comment]
+1

**Comment by TimSimpsonR** [comment]
Is there an incoming RDLI PR?

**Comment by hub-cap** [comment]
@TimSimpsonR, yes thats why it says not to merge it in the comments :D

**Comment by hub-cap** [comment]
Pull request dependent on this https://github.com/hub-cap/reddwarf_lite-integration/pull/69

**Comment by TimSimpsonR** [comment]
+1

**Comment by ed-** [comment]
+1

**Comment by imsplitbit** [comment]
+1

**Pull request merged**
