### PR TITLE
Implemented all of restart, API code for resize.

### PR DESCRIPTION
**Pull request by TimSimpsonR**
This pull request includes the code for restart and much of the code for resize.

### CODE REVIEW

**Comment by rnirmal** [comment]
The diff looks confusing (git does it sometimes)... especially the guest/dbaas.py changes. Looks like you moved a lot of the existing code around. For others looking at the original file might help understand the changes better.

**Comment by cp16net** [comment]
+1 although this will cause mass conflicts with mine. :-/

**Comment by hub-cap** [comment]
geeez... this is a big ole PR. Good luck @cp16net w/ the merge. ugh. I say we just merge this and see how much rework it causes for all of us!

**Comment by TimSimpsonR** [comment]
Yeah, sorry about that. I honestly tried to split it up a bit w/ the smaller pr's first... See you guys on Thursday!

**Comment by ed-** [comment]
+1

**Comment by TimSimpsonR** [comment]
_

**Comment by hub-cap** [comment]
_

**Pull request merged**
