### PR TITLE
Getting the guest status update working.

### PR DESCRIPTION
**Pull request by hub-cap**
- Added the db calls to the guest code
- Changed the default for the confs to use MySQL
- Added HACKISH uuid as a global var for status lookups
- \* This is because the ip is no longer saved
  in the reddwarf db. We can do something
  better in the future since this does
  not persist if the agent stops.

### CODE REVIEW

**Comment by hub-cap** [comment]
This needs a new image build because of a new --addpkg.

**Comment by TimSimpsonR** [comment]
NGUTPR but why was so much code commented out rather than deleted?

**Comment by hub-cap** [comment]
I'm not sure what u mean. I removed a bunch of commented code...

**Comment by TimSimpsonR** [comment]
Sorry, I was a bit mistaken. You left some stuff commented in redstack, but thats not a big deal.

+1

**Comment by cp16net** [comment]
+1

**Comment by ed-** [comment]
+1

**Comment by rnirmal** [comment]
Lets change "uuid" usage to "id"

**Pull request merged**
